### PR TITLE
Corrected more spelling mistakes, finished correcting in Settings and About

### PR DESCRIPTION
**Pull request by hunter1749**
Overall went through more of the app (finished correcting Settings and About for now, and will soon also do so for Controls), corrected some mistakes I've missed before, and again made the text more consistent (less randomly capitalised words, more unified punctiation marks).
The only "visual" change I've made is in the About, where I've added a `<br>` at the end of the STR_ABOUT_INFO_8 string. The text at the top and the bottom still just barely fits on the visible screen so I think it's still fine.

### CODE REVIEW

**Comment by hunter1749** [comment]
When correcting US language in Controls, I renamed all "PP" and "Picture Picture" to "picture in picture", so it's the same throughout the entire app. The only visual changed I've made was adding three `<br>` tags, one before each new title in the Controls.

Something I've missed (and still haven't fixed) in the Settings before is that the "Content language" can be set to "All", and when it is (I think it is default), the "Content language" is actually "English [EN]", so I think this is a small visual bug, perhaps changing the string's array would fix it.

**Comment by fgl27** [comment]
Do not make any visual changes as to as be

The app has an global font size option, if you set that to 3 some things will not be visible

There is this I prefers to be on caps.

So I revise this when I have time

**Comment by hunter1749** [comment]
Alright, sure, also didn't really think about different font sizes so feel free to just remove all those br tags I added.

**Comment by fgl27** [comment]
Also the content language all is all languages, there is just too many en content and they are the most popular

**Comment by fgl27** [comment]
> Alright, sure, also didn't really think about different font sizes so feel free to just remove all those br tags I added. And I did add quotes on some of them, but not all I don't think.

You can just make another commit in the same branch will show on this pull request.

You can also just drag and drop images files on comments, no need for external image links.

**Comment by fgl27** [comment]
Another thigh you don't add HTML elements as 'be' to the string in the lang file

But add it to this file

https://github.com/fgl27/SmartTwitchTV/blob/master/app/languages/default.js

Add it it with a '+= STR_BR'

**Comment by hunter1749** [comment]
Okay, I only did it because I saw that some other strings already had
the br tag. I'll do it your way in the future.

V V pon., 12. jul. 2021 ob 23:56 je oseba Felipe Leon <
***@***.***> napisala:

**Comment by fgl27** [comment]
Yes I get it don't worry, this strings implementation are a little confusing.

I have added this

https://github.com/fgl27/SmartTwitchTV/blob/master/app/languages/default.js#L160

for strings that need a line break at the end of it

**Comment by hunter1749** [comment]
Alright, thanks. Also, I have some UI suggestions, no worries if you don't
like them, but I'd just like to share what I thought of. The first image
would be a completely different design (probably never going to be added,
since it would also require quite a lot of reprogramming, especially
because it wouldn't be a side menu, but I could make it a side menu if even
want any changes), and the other image is just a small improvement of the
current one (lighter text like that "Live" text at the top, no side menu
right border, no side menu transparency, overall less borders like
currently when you focus a live preview you get a white border around it,
maybe some icons could be modified too so they looks lighter as well). I
saw that you put a lot of thought into the accessibility part of the
design, which is nice (I think I saw some css styling for protecting from
burn-in), and also it has a lot of options to customise it for yourself
(like the youtube tv app has all the options in one tab because there
aren't that many, and they also don't have any shortcuts there), so maybe
that's why it's harder to make this app look nicer, but I hope we can maybe
figure something out if you're up for it.
[image: image.png]
[image: image.png]

V V tor., 13. jul. 2021 ob 22:35 je oseba Felipe Leon <
***@***.***> napisala:

**Comment by fgl27** [comment]
I can't see any image.
check the web site

https://github.com/fgl27/SmartTwitchTV/pull/51

I don't know how you send it but emails don't work well on comment as to comment on the site it self

**Comment by hunter1749** [comment]
Yeah I thought it might not send. Anyway, this should work
https://i.imgur.com/SZR9a8Q.png https://i.imgur.com/DT4VrJs.png

V V sre., 14. jul. 2021 ob 02:43 je oseba Felipe Leon <
***@***.***> napisala:

**Comment by fgl27** [comment]
I can see the images now

The app had a different look in the past with a top bar

img_old look

But I change it last year, current navigation layout is something that I plan to keep as is something that is used on most TV apps, I just wanna something simple to use but that allow a level of customization and features.

Take too much time to create this type of layout and styles, I don't plan to make that big of changes.

But if someone wanna to make something that allows current and a different style to work in the app by adding a option to settings that allows for layout change I accept, I'll just not make it.

Have you see this setting option? from the images bellow

Screenshot from 2021-07-15 05-24-05

Screenshot from 2021-07-15 05-24-06

They allow you to use a custom style for a thumbnail.

I will add some improve to the side panel, but I will not change the default style for the thumbnails as this is something the user already can do.

Thanks for the help, I really appreciate it.

**Comment by hunter1749** [comment]
Oh, I did see the thumbnail customisation before, but I didn't know you
could make it that different, thanks anyway.

V V čet., 15. jul. 2021 ob 10:26 je oseba Felipe Leon <
***@***.***> napisala:

**Pull request merged**
